insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());

insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());insert into tb_category (name, created_at) values ('Books', now());
insert into tb_category (name, created_at) values ('Electronics', now());
insert into tb_category (name,  created_at) values ('Computers', now());